---
title: "Group 9 Lab 2"
author: "Brianna Lawton"
date: "February 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Group 9 Lab 2 Markdown

Link to our repo: https://github.com/brlaw17/Group9-Lab2.gi

```{r cars}
#install sf package
#install.packages("sf")
library(ggplot2)
library(sf)

## Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3
p <- ggplot() +
  geom_sf(data = read_sf("Data/ME-GIS-master/Coastline2.shp"), 
          colour="grey10", fill="grey90") +
  geom_sf(data = read_sf("Data/ME-GIS-master/Rivers19.shp"), 
          colour="steelblue", size=0.3) +
  geom_sf(data = read_sf("Data/ME-GIS-master/PrimaryRoads.shp"), 
          size = 0.7, colour="grey30") +
  geom_sf(data = read_sf("Data/ME-GIS-master/Cities.shp")) +
  theme_bw()
p

```

## Mre Map Elements

```{r}
#install.packages("ggspatial")
library(ggspatial)
p + geom_sf_text(data = read_sf("Data/ME-GIS-master/Cities.shp"), aes(label = Name)) + 
  theme_bw() +
annotation_scale (location = "bl") +
annotation_north_arrow(which_north = "grid", location = "tr")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
